## TODO: add a compose examples directory with various deployment options.
version: "3"
services:
  redis:
    image: redis
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data"
#  ohmyform:
#    build: .
#    environment:
#      CREATE_ADMIN: "TRUE"
#      MONGODB_URI: mongodb://mongo/ohmyform
#      MAILER_URI: smtp://mail:1025
#      PORT: 5000
#    links:
#      - mongo
#      - redis
#      - mail
#    ports:
#      - "5200:5000"
#    depends_on:
#      - mongo
#      - redis
  ui:
    image: ohmyform/ui
    environment:
      API_HOST: http://localhost:5100/graphql
      PORT: 5000
    ports:
      - "5000:5000"
  api:
    image: ohmyform/api
    environment:
      CREATE_ADMIN: "true"
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://mail:1025
      REDIS_URL: redis://redis
      PORT: 5000
    links:
      - mongo
      - redis
      - mail
    ports:
      - "5100:5000"
    depends_on:
      - mongo
      - redis
  mail:
    image: mailhog/mailhog
    ports:
      - "5050:8025"
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "5051:8081"
    links:
      - mongo
    depends_on:
      - mongo
